### ISSUE TITLE
Firestore in Native or Datastore mode?

### ISSUE THREAD

**Issue by Molnfront** [kiyohken2000/ReactNative-Expo-Firebase-Boilerplate-v2#5]
Hi,
great project you have!

One question:

Do you run Firestore in Native mode or Datastore mode?

I assume that it's Native mode, based on the sdk you use!

**Comment by kiyohken2000** [comment]
Yes. This project is a firestore native mode.

**Comment by Molnfront** [comment]
Ok great!

You can close this.
